{...}: {
  imports = [
    ./devicons.nix
    ./completions.nix
    ./conform.nix
    ./dressing.nix
    ./fugitive.nix
    ./git.nix
    ./lsp.nix
    ./lualine.nix
    ./mini.nix
    ./neo-tree.nix
    ./oil.nix
    ./telescope.nix
    ./tmux-navigator.nix
    ./which-key.nix
    ./treesitter.nix
    ./auto-session.nix
    ./tailwindcss-colors.nix
    ./lazydocker.nix
    ./live-server.nix
    ./matchup.nix
    ./surround.nix
    ./trouble.nix
    ./bqf.nix
    ./ufo.nix
    ./indent-blankline.nix
    ./statuscol.nix
    ./harpoon.nix
  ];
}
